### ISSUE TITLE
CMake Order of Arguments Issue

### ISSUE THREAD

**Issue by ericspod** [BioMedIA/MIRTK#259]
I wasn't able to compile the most recent code on Ubuntu 14.04 with cmake version 2.8.12.2 until I reversed the order of arguments to function basis_install() in CMake/Modules/CMakeLists.txt. This puts the DESTINATION value second which appears to be required by cmake (or at least my version). Having made this change I can compile the default configuration correctly.

**Comment by schuhschuh** [comment]
Thanks, that seems reasonable it fails with older CMake versions. Was not an issue with CMake 3.3 and later which I used for testing. Also the Travis CI build uses the Ubuntu 14.04 Trusty environment with default CMake installation which I assumed would be CMake 2.8.12.2, but maybe they've installed a more recent version. Not listed in their documentation.

Does the following work instead of changing the order of arguments?

You find the `basis_install` function in `CMake/Basis/InstallationTools.cmake` around line 44. Would be more flexible to fix it this way. Then the order doesn't matter for either CMake version (and `basis_install_directory` is called for `basis_install(DIRECTORY)`).
```cmake
function (basis_install)
  cmake_parse_arguments (ARGN "" "DIRECTORY" "TARGETS;FILES;PROGRAMS" ${ARGN})
  set (_mutual_exclusive_errmsg "Options TARGETS, FILES, PROGRAMS, and DIRECTORY are mutually exclusive!")
  if (ARGN_DIRECTORY)
    if (ARGN_FILES OR ARGN_PROGRAMS OR ARGN_TARGETS)
      message (FATAL_ERROR "${_mutual_exclusive_errmsg}")
    endif ()
    basis_install_directory (${ARGN_DIRECTORY} ${ARGN_UNPARSED_ARGUMENTS})
  elseif (ARGN_FILES)
    if (ARGN_PROGRAMS OR ARGN_TARGETS OR  ARGN_DIRECTORY)
      message (FATAL_ERROR "${_mutual_exclusive_errmsg}")    endif ()
    install (FILES ${ARGN_FILES} ${ARGN_UNPARSED_ARGUMENTS})
  elseif (ARGN_PROGRAMS)
    if (ARGN_FILES OR ARGN_TARGETS OR  ARGN_DIRECTORY)
      message (FATAL_ERROR "${_mutual_exclusive_errmsg}")    endif ()
    install (PROGRAMS ${ARGN_PROGRAMS} ${ARGN_UNPARSED_ARGUMENTS})
  elseif (ARGN_TARGETS)
    if (ARGN_FILES OR ARGN_PROGRAMS OR ARGN_DIRECTORY)
      message (FATAL_ERROR "${_mutual_exclusive_errmsg}")
    endif ()
    install (TARGETS ${ARGN_TARGETS} ${ARGN_UNPARSED_ARGUMENTS})
  else ()
    install (${ARGN_UNPARSED_ARGUMENTS})
  endif ()
endfunction ()
```

**Comment by ericspod** [comment]
Yeah older CMake would explain things, I had just installed the version that came with 14.04 so didn't check if it was up-to-date or not. Your changes do work however (in that the Configure stage in CMake-gui goes through correctly) so it shouldn't be a problem now. Thanks!

**Comment by schuhschuh** [comment]
I've just tried it with my CMake 2.8.12.2 on Ubuntu 14.04 and I cannot reproduce this CMake build configuration issue.
