### ISSUE TITLE
Segmentation fault in GenericRegistrationFilter::InitializePyramid

### ISSUE THREAD

**Issue by bnasihatkon** [BioMedIA/MIRTK#67]
Hi, 

I am trying to get mirtk work under my ubuntu 64bit machine. I was able to compile the source. But when I run the register command I get a "segmentation fault" error. This is what I run

mirtk register image0.nii image1.nii -parin a.par -dofout out.txt 

I tracked the error down to a tbb function call
parallel_for(pyramid, resample);
at line 2393 of
Modules/Registration/src/mirtkGenericRegistrationFilter.cc

I recompiled with the WITH_TBB config option, but the issue persisted. 

Can anyone help me? 
Thanks.

**Comment by schuhschuh** [comment]
Hi @bnasihatkon, could you also post your parameters file ```a.par```?

**Comment by bnasihatkon** [comment]
Thanks for your prompt response, I use the following sample file
https://github.com/ledigchr/MALPEM/blob/master/lib/pincram/lev1.cfg
(I hope this a valid parameters file)

just realised that the error goes away by commenting out the last line (Resolution = 3 3 3). 
Thanks,

**Comment by schuhschuh** [comment]
Thanks, the reason the error goes away when you remove this line is probably because without an explicit resolution specification of your pyramid, the registration filter uses a default Gaussian pyramid. Hence, it executes a different code path in ```GenericRegistrationFilter::InitializePyramid```.

We should still try and find the actual cause for the segmentation fault. Therefore I would need your input images. As you identified where the segmentation fault occurs, I assume you have a Debug build and run it in a debugger already? I suggest building with either WITH_TBB = OFF, or to run it with the option ```-threads 1``` in a debugger to see what code in particular causes the crash. It must be some particular line in ```ResampleImages::operator()``` (around lines 318-346). First I would check that the indices ```l``` and ```n``` are within bounds when accessing the ```_Image``` to be resampled. You can also run the program with ```-v 3``` to enable the highest level of verbose command output.

**Comment by bnasihatkon** [comment]
Hi, 
I further tracked it to the command 
_Buffer->CopyFrom(_Output->Data());
in
void ImageToImage<VoxelType>::Finalize()
at
mirtkImageToImage.cc

The input files are too big to attach. But you can get them from this dropbox link:
https://www.dropbox.com/sh/sy46lu11vv9127k/AABv6W5p8yLD8NopcS-WbXsKa?dl=0

**Comment by schuhschuh** [comment]
Thanks, that helps. This bug should be fixed in the develop branch already. Which Git branch have you checked out?

**Comment by bnasihatkon** [comment]
master

**Comment by schuhschuh** [comment]
Please use the develop branch. Should be working fine then.

```
git checkout develop
git submodule update
```

**Comment by schuhschuh** [comment]
P.S.: I suggest the extension ```.dof``` or ```.dof.gz``` for MIRTK transformation files. These have a binary format.

**Comment by bnasihatkon** [comment]
Yes, it works now. Thanks.
