### ISSUE TITLE
evaluate-overlap: unexpected results in summary measure

### ISSUE THREAD

**Issue by soundray** [BioMedIA/MIRTK#696]
Taking IRTK `labelStats` as reference
```
$ labelStats ref.nii.gz com.nii.gz -q
0.630565,0.76028
```
This is what's expected. `seg_stats` arrives at a higher value, because it considers label 0 (0.99), but it's in the same ballpark
```
$ seg_stats ref.nii.gz -d com.nii.gz | grep Mean
Mean Dice = 0.762674
```
Now for MIRTK
```
$ evaluate-overlap ref.nii.gz com.nii.gz 
Error: Input images must be sampled on same lattice!
```
The difference is in the voxel size in t, which should not matter in 3D images. `edit-image` won't fix it (#695) unless one uses `-reset`:
```
$ edit-image ref.nii.gz ref.nii.gz -reset
$ edit-image com.nii.gz com.nii.gz -reset
$ evaluate-overlap ref.nii.gz com.nii.gz 
Average SI = 0.832208
```
Expected SI value is 0.76028. Is there any weighting going on?

An option to show OR (Jaccard/Tanimoto / intersection over union) instead or in addition would be useful.

Overlaps for individual labels are determined correctly
```
mirtklabelstats () { # Function to imitate labelstats im1 im2 -false
    ref=$1 ; tst=$2 ;
    evaluate-overlap $ref $tst -labels -table stdout -precision 6 | tail -n +2
    | tr , ' '
    | while read label tp fn fp tn tpr tnr dsc jsc ; do
        echo $label,$[$tp + $fn],$[$tp + $fp],$tp,$fn,$fp,$jsc,$dsc
    done
}
$ labelStats ref.nii.gz com.nii.gz -false >irtk-labelstats.csv
$ mirtklabelstats ref.nii.gz com.nii.gz > mirtk-labelstats.csv
$ diff irtk-labelstats.csv mirtk-labelstats.csv
$ 
```

Just that `evaluate-overlap` is quite slow
```
$ time labelStats ref.nii.gz com.nii.gz -false >irtk-labelstats.csv

real    0m0.281s
user    0m0.148s
sys     0m0.039s
$ time mirtklabelstats ref.nii.gz com.nii.gz > mirtk-labelstats.csv

real    0m15.946s
user    0m15.793s
sys     0m0.042s
```

**Comment by schuhschuh** [comment]
Could it be that the unexpected SI value from `evaluate-overlap` is because it is not a segmentation overlap measure as you expect? By default, this command treats the input images as two intensity volumes (e.g., brain MR images) rather than segmentation label images. This is for historic reasons, based on the behavior of the corresponding original IRTK tool [overlap](https://github.com/BioMedIA/IRTK/blob/master/applications/overlap.cc).

For segmentation label images, you must either tell the program to compute the overlap for all labels by giving the single option `-labels`, or you can specify ROIs by merging labels using the `-segment` (or `-label`) option with a list of labels. This option can be given multiple times to specify multiple segments. Each segment is treated as one label for the purposes of overlap computation. For example, given a segmentation for 1: WM, 2: deep GM, 3: cortical GM, you could get two overlap measures for WM and (dGM+cGM) segments using `-segment 1 -segment 2 3`.

**Comment by schuhschuh** [comment]
Looking at your post, I guess you are already aware of `-labels` and similar options.

I've compared the code of MIRTK's `evaluate-overlap` to IRTK's `overlap` tool, and it seems both are more or less identical. You would probably get the same SI value with IRTK. Could the weighting you were asking about be this: `w = histogramA(i) / double(histogramA.NumberOfSamples() - histogramA(0))`?

**Comment by soundray** [comment]
Okay, that explains it. I wasn't aware of the `overlap` tool in IRTK, but it gives the identical result for the ref-com pair above. Thank you!
