### ISSUE TITLE
intensity scaling in construct-atlas

### ISSUE THREAD

**Issue by alenauus** [BioMedIA/MIRTK#731]
Sorry, is there is a way to switch off intensity scaling for atlas construction?

Thank you.

Best wishes,
Alena

**Comment by schuhschuh** [comment]
Hi Alena, yes, there is. In the configuration file of the atlas, the `rescaling` entry is simply passed on to `average-images`. I think you can set this configuration entry to "none" (`null` might also work instead of a string value) to disable the rescaling.

See [average-images help on -rescale option](https://github.com/BioMedIA/MIRTK/blob/f72329eb4e7ace008f772ec150d210c301515d88/Applications/src/average-images.cc#L128).

See [example construct-atlas configuration with rescaling parameter](https://github.com/MIRTK/BAtCh/blob/c4f8fcb3d42fc2671862fc466b7461c12ab734f3/config/dhcp-2019/09-n340-bet-masks-adaptive-sigma.json#L18).
